# This file was generated by GoReleaser. DO NOT EDIT.
cask "lore" do
  version "0.7.3"

  on_macos do
    on_arm do
      sha256 "6d50ac50047e1d51b6fc4aab509ce53f4c5d29e438a9e144595a42823d6ae7cd"
      url "https://github.com/aakarim/OpenLore/releases/download/v#{version}/openlore_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "10eab852c5ec2f156f65cd492ae177b54517ade9ff7eb3eaf490b8b72a9d41fa"
      url "https://github.com/aakarim/OpenLore/releases/download/v#{version}/openlore_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4889b345ab571051ca3e20feac312df67002e0d5cbf5ad649b355e034b76057"
      url "https://github.com/aakarim/OpenLore/releases/download/v#{version}/openlore_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2aa343e5a163a4a91c2ff5095f6d89008c4d00c3225af8fd80116475927664af"
      url "https://github.com/aakarim/OpenLore/releases/download/v#{version}/openlore_linux_amd64.tar.gz"
    end
  end

  name "lore"
  desc "Agent-native knowledge base that keeps shared context current and inspectable"
  homepage "https://github.com/aakarim/OpenLore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openlore"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "openlore"], chdir: "."
    end
  end

  # No zap stanza required
end
